hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
shot test/shots/battle1.ppm
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
hold A 2
wait 26
shot test/shots/battle2.ppm
